export const ACTIONS = {
	ALERT_POP: 'ALERT_POP'
}

export const PLAYER_ACTIONS = {
	CREATE_PLAYER: 'CREATE_PLAYER',
	UPDATE_PLAYER: 'UPDATE_PLAYER'
}

export const ROOM_ACTIONS = {
	ADD_ROOM: 'ADD_ROOM',
	DELETE_ROOM: 'DELETE_ROOM',
	UPDATE_ROOM: 'UPDATE_ROOM'
}