export const SOCKET_RES = {
	PLAYER_CREATED: 'PLAYER_CREATED',
	PLAYER_NAME_EXIST: 'PLAYER_NAME_EXIST',
	PLAYER_NOT_EXIST: 'PLAYER_NOT_EXIST',
	ROOM_CREATED: 'ROOM_CREATED',
	ROOM_NAME_EXIST: 'ROOM_NAME_EXIST',
	ROOM_DOESNT_EXIST: 'ROOM_DOESNT_EXIST',
	ROOM_UPDATED: 'ROOM_UPDATED',
	ROOM_DELETED: 'ROOM_DELETED'
}

export const SOCKET_EVENTS = {
	CREATE_PLAYER: 'CREATE_PLAYER',
	FECTH_ALL_ROOM: 'FECTH_ALL_ROOM',
	CREATE_ROOM: 'CREATE_ROOM',
	UPDATE_ROOM: 'UPDATE_ROOM',
	DELETE_ROOM: 'DELETE_ROOM'
}
